### PR TITLE
Add Hagezi Threat Intelligence Feeds

### PR DESCRIPTION
**Pull request by yokoffing**
Hey @romaincointepas,

Thank you for merging a previously popular pull request: https://github.com/nextdns/blocklists/pull/65. By extension, many of us would also like to also have Hagezi's Threat Intelligence Feeds (TIF) to compliment our other blocklists.

Please offer @hagezi's TIF blocklist as an option. Details: https://github.com/hagezi/dns-blocklists#tif

Thanks for your support,

yokoffing
Maintainer of [NextDNS Config](https://github.com/yokoffing/NextDNS-Config) guide

### CODE REVIEW

**Comment by RaggyShaggy** [comment]
Would love to see it.

**Comment by fynks** [comment]
It would be best

**Comment by hagezi** [comment]
Good luck ;)

**Comment by mvnixon** [comment]
please add

**Comment by dartsmaster** [comment]
This would be an excellent addition to the blocklists.

**Comment by BoDoPs** [comment]
Yes, this would be a great add.

**Comment by ericafterdark** [comment]
Has my vote!

**Comment by Spark4000** [comment]
C`mon NextDNS, make it happen

**Comment by FookunKlez** [comment]
Yes please

**Comment by hmbarbosa** [comment]
Awesome job!!!

**Comment by miltonjsvidal** [comment]
Thanks for this!!

**Comment by kaiden87** [comment]
Yes, definitely!

**Comment by thiendt2k1** [comment]
Dont even know if they are keeping tab on this whole filter lists topic, i request 3 or 4 different blocklists but none got respond. Shame on NextDNS!

**Comment by live4swell** [comment]
👍🏻

**Comment by gautaus** [comment]
:+1:

**Comment by adamk1211** [comment]
Yes please.

**Comment by wengkitttt** [comment]
Please add this blocklist !

**Comment by jimvajda** [comment]
Pretty please?

**Comment by Sandbox8888** [comment]
Please add.

**Comment by BourbonCrow** [comment]
Please add this

**Comment by 0xvino** [comment]
Nextdns pls add this (I'm a paid nextdns user)

**Comment by DragonWolf5589** [comment]
This is one of the top features I would like implementing to next dns.

Even if they can't add this exact list allow us a way to import custom ones so we can do it ourselves!

**Comment by LunaticBFF57** [comment]
Been like 6 weeks and no response from dev team?

**Comment by hagezi** [comment]
Available in AdGuardDNS, ControlD, RethinkDNS and DNSwarden.

**Comment by live4swell** [comment]
Any idea what NextDNS uses as their source for threat intelligence feeds?

**Comment by LunaticBFF57** [comment]
> Any idea what NextDNS uses as their source for threat intelligence feeds?

They use "a blend of the most reputable threat intelligence feeds". (Direct quote from website.) It will most likely continue being a secret because of 'trade secrets'.

**Comment by serqrevp** [comment]
Please add the TIF list.

**Comment by wengkitttt** [comment]
It's been 12 weeks since this pull request was opened. @romaincointepas Please consider merging this pull request. We all hope the Hagezi Threat Intelligence Feeds are include in NextDNS. Thank You.

**Comment by wengkitttt** [comment]
Hey @romaincointepas,

Hope you're doing well! It's been 12 weeks since @yokoffing opened this pull request. Any chance to get it merged? We're all pretty excited about the Hagezi Threat Intelligence Feeds being part of NextDNS.

If there's any hiccup or reason you can't merge it, please let us know. We'd really appreciate it!

Thanks you.

**Comment by BourbonCrow** [comment]
> Hey @romaincointepas,
> 
> Hope you're doing well! It's been 12 weeks since @yokoffing opened this pull request. Any chance to get it merged? We're all pretty excited about the Hagezi Threat Intelligence Feeds being part of NextDNS.
> 
> If there's any hiccup or reason you can't merge it, please let us know. We'd really appreciate it!
> 
> Thanks you.

It has been months since any updates on any of their repositorys. Without any word, I mean sure they have never been good at communicating but posting like 4 words or something on X or whatever social media they prefer letting ppl know what's going on sometimes would be nice.  Not asking for a essay, only sign of life at this point haha

**Comment by LunaticBFF57** [comment]
> > Hey @romaincointepas,
> > Hope you're doing well! It's been 12 weeks since @yokoffing opened this pull request. Any chance to get it merged? We're all pretty excited about the Hagezi Threat Intelligence Feeds being part of NextDNS.
> > If there's any hiccup or reason you can't merge it, please let us know. We'd really appreciate it!
> > Thanks you.
> 
> It has been months since any updates on any of their repositorys. Without any word, I mean sure they have never been good at communicating but posting like 4 words or something on X or whatever social media they prefer letting ppl know what's going on sometimes would be nice. Not asking for a essay, only sign of life at this point haha

@BourbonCrow, @romaincointepas may be working on [DNS0.EU](www.dns0.eu).

**Comment by LudnicaKiller** [comment]
Would love to see it 😊

**Comment by wengkitttt** [comment]
Still no response from the dev 💀

**Comment by LunaticBFF57** [comment]
Are there any other devs that can commit to this repo?

**Comment by ittairuf** [comment]
@romaincointepas please give us an update.

**Comment by DragonWolf5589** [comment]
Its no wonder people are moving away/saying nextdns is "abandoned" im thinking if switching to a competitor one of these days qnd free setting everything up again if they dont add this or at LEAST show they are active/still supporting nextdns.

**Comment by BourbonCrow** [comment]
> Its no wonder people are moving away/saying nextdns is "abandoned" im thinking if switching to a competitor one of these days and rsetting everything up again if they dont add this or at LEAST show they are active/still supporting nextdns.
> 
> (edit: spelling mistake)

I'm annoyed with them being 100% just vanished and dont deal with old issues like removing old out dated filters and removing the outdated filters from their main filter and their list where you add your own domains whitelist and blocklist could be a bit better so you could add multiple domains.. and even like control D to organize in folders would be great with a import export. so I'm currently trying out ControlD a bit while i montitor the situation over at nextdns
pros:
- UI is nice and easy to work with
- easy to add / import your own lil list of domains or TLD's no need to input them 1 by 1, 
- they do have all the hagezi stuff including the TIF

cons:
- i would say their own filters seems a bit of a mess atm way to many false positives on their crypty/malware (they seem pretty fast at fixing the reports on discord)

**Comment by wengkitttt** [comment]
@BourbonCrow I tried ControlD too, it took some time to get used to their UI. The dev team listens to their customers, and any issues are solved quickly. But, too bad I can't make the switch because I'm living in Asia, and the servers in Asia are quite bad when compared with NextDNS. I hope ControlD can increase and improve their servers in the Asia region.

By the way, if you guys go check out NextDNS other repository, there is still ongoing development, which means they can actually look into the issues in this repository, but they choose to ignore it? I'm not sure.

I wish the NextDNS dev team can have some response to this PR.

**Comment by BourbonCrow** [comment]
> @BourbonCrow I tried ControlD too, it took some time to get used to their UI. The dev team listens to their customers, and any issues are solved quickly. But, too bad I can't make the switch because I'm living in Asia, and the servers in Asia are quite bad when compared with NextDNS. I hope ControlD can increase and improve their servers in the Asia region.
> 
> By the way, if you guys go check out NextDNS other repository, there is still ongoing development, which means they can actually look into the issues in this repository, but they choose to ignore it? I'm not sure.
> 
> I wish the NextDNS dev team can have some response to this PR.

@wengkitttt sweden ping on controld is like 30~ and nextdns is like..13 cause nextdns got servers in sweden but in for me non of the latencys are noticable cause both are very long, but i hope for you that they add a asian server.

also even if they dont wanna write massive blob posts.. i think next dns ppl could atleast spend... 10 min per month or.. less writing like a 15 word post on twitter or .. whatever social media they prefer  just small updates letting us know whats going on. not asking for a essay or anything.. could just be like "We currently busy with dns0 eu so our work with next dns will slow donwn for a while" something simple like that would satesfy me and prolly alot of other ppl as well. cause its better knowing than just wondering forever not knowing anything

**Comment by nemchik** [comment]
https://github.com/nextdns/nextdns does not seem abandoned. I am not sure the status of this repository. It's possible different contributors responsible may not have visibility here vs the other repo that has a little more activity.

**Comment by ittairuf** [comment]
Hello @rs @romaincointepas, could you please check this?

**Comment by hagezi** [comment]
@rs @romaincointepas could you at least give feedback to the community? Zero response for months. But it's not that difficult: yes, no, don't know would be enough.

@yokoffing If you don't get any feedback, just close the PR.

Gerd

**Comment by unknown4849** [comment]
https://help.nextdns.io/t/60yqxb9?r=m1y8n0m

and after ±6 month, got the answer.

**Comment by live4swell** [comment]
Should respond with the same thing on the NextDNS discussion forum, maybe they will respond...maybe not

**Comment by wengkitttt** [comment]
I'm not an expert in this, but may I ask why it is so hard for them to add the Hagezi TIF list? Is it the format of the list? Or are there any policy issues that are stopping them?

I believe many NextDNS users want this list to be added, and some of their customers are leaving to go for other alternatives that have this list included, like AdGuardDNS, Controld, etc.

**Comment by DragonWolf5589** [comment]
Wow an update after 6 months.. Now inonow what hagazi removed nexydns as a recommended service and why evwryone is moving to adguard and controlD instead. Guess ill be doing the same after my paid nextdns ends and moving all my friends/family too.

**Comment by DragonWolf5589** [comment]
> I'm not an expert in this, but may I ask why it is so hard for them to add the Hagezi TIF list? Is it the format of the list? Or are there any policy issues that are stopping them?
> 
> I believe many NextDNS users want this list to be added, and some of their customers are leaving to go for other alternatives that have this list included, like AdGuardDNS, Controld, etc.

All they said is "we only add privacy lists and use our own TIF"

Seems ill be joining everyone else leaving to another servicr once my paid year is up

**Comment by live4swell** [comment]
> Wow an update after 6 months.. Now inonow what hagazi removed nexydns as a recommended service and why evwryone is moving to adguard and controlD instead. Guess ill be doing the same after my paid nextdns ends and moving all my friends/family too.

Does the service not work as intended? Do you have issues? I think those should be reasons for switching not silence from the company especially when things just work.

**Comment by unknown4849** [comment]
> Does the service not work as intended? Do you have issues? I think those should be reasons for switching not silence from the company especially when things just work.

the services still working, so no need worry, but now they only at maintenace mode no update or new feature or remove outdate blocklist ( i mean maintain this github repo)

**Comment by rs** [comment]
Please check this thread: https://www.reddit.com/r/nextdns/comments/1cika3o/comment/l2cidps/

**Comment by ExtRIELICi** [comment]
Please reconsider, adding HaGeZi's full TIF would be extremely beneficial to a lot of users. @rs @romaincointepas

**Comment by hagezi** [comment]
FYI: https://github.com/hagezi/dns-blocklists/issues/4633

**Pull request closed without merging**
