### PR TITLE
Add HaGeZi Blocklists

### PR DESCRIPTION
**Pull request by hagezi**
Hi @romaincointepas,
as requested my pull request in the new repository.

As requested by the users, I have added all versions of my blocklists. Light, Normal, Pro, Pro++ and the new Ultimate.
So no wishes should remain unfulfilled.

Details: https://github.com/hagezi/dns-blocklists

Thanks for your support,
Gerd

### CODE REVIEW

**Comment by sngmrrsy** [comment]
@hagezi Did you receive any updates from the dev on this pull? or is @nextdns development dead

**Comment by sngmrrsy** [comment]
@romaincointepas Please add? It's been a month, 2 if you count the other threads made on forum.

**Comment by hagezi** [comment]
> @hagezi Did you receive any updates from the dev on this pull? or is @nextdns development dead
No updates ...

**Comment by sngmrrsy** [comment]
> > @hagezi Did you receive any updates from the dev on this pull? or is @nextdns development dead
> 
> No updates ...

Damn. Good list tho. Maybe I'll change to another DNS.

**Comment by GiddyGoatGaming** [comment]
> > > @hagezi Did you receive any updates from the dev on this pull? or is @nextdns development dead
> > 
> > 
> > No updates ...
> 
> Damn. Good list tho. Maybe I'll change to another DNS.

If you do, check out rethinkdns and dnswarden. Although you can’t applies specific domain whitelists, there is far more blocklists. dnswarden has all of hagezi’s lists except ultimate which is coming soon and rethinkdns has pro, pro++ and ultimate

**Comment by RainmakerRaw** [comment]
I'm running AdGuard Home on a VPS just so I can use Hagezi's list. I'm seriously reconsidering paying for NextDNS next time my sub comes due. Many lists are old, out of date or dead (Energized), meanwhile what is probably the best compilation list on the Internet hangs in the ether... Come on NextDNS, sort it out - this isn't a free service, we deserve better quality (*cough* Hagezi *cough*).

**Comment by GiddyGoatGaming** [comment]
> I'm running AdGuard Home on a VPS just so I can use Hagezi's list. I'm seriously reconsidering paying for NextDNS next time my sub comes due. Many lists are old, out of date or dead (Energized), meanwhile what is probably the best compilation list on the Internet hangs in the ether... Come on NextDNS, sort it out - this isn't a free service, we deserve better quality (_cough_ Hagezi _cough_).

Exactly, even nextdns threat intelligence is getting a little lackluster since there’s lists like hagezi’s threat intelligence which does what mostly all those lists do at a smaller size, there’s phishing army extended and there’s the blocklist projects malware list

**Comment by sngmrrsy** [comment]
> I'm running AdGuard Home on a VPS just so I can use Hagezi's list. I'm seriously reconsidering paying for NextDNS next time my sub comes due. Many lists are old, out of date or dead (Energized), meanwhile what is probably the best compilation list on the Internet hangs in the ether... Come on NextDNS, sort it out - this isn't a free service, we deserve better quality (_cough_ Hagezi _cough_).

This service seems dead. No respond from devs on email, git and even their own forum. Probably the right time to shift somewhere else

**Comment by yokoffing** [comment]
@hagezi, while we wait, can we throw [Threat Intelligence Feeds](https://github.com/hagezi/dns-blocklists#threat-intelligence-feeds---increases-security-significantly-) (TIF) into this batch? for all the folks who won't use Ultimate.

**Comment by hagezi** [comment]
@yokoffing I'm happy to do that, however, besides AI, they really only use native lists and various services for TIF, not compilations. At least as far as I know.

Maybe @romaincointepas, @rs or @NextDNS support can say something about this?

**Comment by yokoffing** [comment]
> Still hoping that NextDNS will approve these lists very soon...

I may or may not be testing out ControlD 👀

**Comment by hagezi** [comment]
Since there is no reaction or any feedback, I will close the pull request next week.

**Comment by ijuliank** [comment]
Ask it at adguard

**Comment by lyrad87** [comment]
@romaincointepas can you please merge this pull request? Lots of users would love to use hagezi's list.

**Comment by romaincointepas** [comment]
@hagezi those are now live on NextDNS.

**Comment by hagezi** [comment]
@romaincointepas Thanks.

**Comment by devipasigner** [comment]
@romaincointepas Awesome! Thanks for me so active lately. I have a question, why wasn’t the threat list added? I recommend it, can fully vouch it it’s a very good list I’m using on adguard home

**Comment by yokoffing** [comment]
> why wasn’t the threat list added?

Hagezi didn't make a pull request for it.

**Comment by sngmrrsy** [comment]
Finally!

**Comment by devipasigner** [comment]
> > why wasn’t the threat list added?
> 
> Hagezi didn't make a pull request for it.

I see. I thought one of you had. Regarding your recommendation, is there a reason why pro isn’t recommend for balanced instead of normal? It’s not a lot stricter in my testing but if you share a different view that’s ok

**Comment by devipasigner** [comment]
> Finally!

Really. Love to see updates!

**Comment by yokoffing** [comment]
> @devipasigner is there a reason why pro isn’t recommend for balanced instead of normal?

`Pro` is prone to more false positives because of its inclusion of NoTracking. See discussion: https://github.com/hagezi/dns-blocklists/issues/64.

> It’s not a lot stricter in my testing

True. If you find yourself between Normal and Pro++, then just use Pro 🤷

**Pull request merged**
