### PR TITLE
Remove Energized blocklists

### LINKED ISSUE #84: Remove Dead Blocklists
The following blocklists are dead (they show 0 entries in NextDNS) and should either be updated or removed:
Energized Spark
Energized Ultimate
Energized Xtreme Extension
Energized Blu
Energized Basic

image

Thanks

### PR DESCRIPTION
**Pull request by chr-lei**
Resolves #84  - This PR should remove the json files for the Energized block lists as they are not currently being maintained, the source files are not accessible, and many have 0 entries.

### CODE REVIEW

**Comment by jmcglock** [comment]
When will this get merged?

**Comment by quantumpacket** [comment]
They've been trying to [decide](https://github.com/nextdns/metadata/pull/1148#issuecomment-1335949992) on this since December. :roll_eyes:

**Comment by chr-lei** [comment]
@romaincointepas , is there anything I can do to make this PR more acceptable for NextDNS to merge?  If NextDNS has decided to continue to keep the inactive/broken lists intact after the [discussion referenced](https://github.com/nextdns/metadata/pull/1148#issuecomment-1335949992) in the metadata repo I can just close this PR.

**Comment by chr-lei** [comment]
@romaincointepas Just wanted to check one more time to see if there's something I can do here to help advance this; or if you'd like me to just close this PR. Thanks!

**Comment by chr-lei** [comment]
Sorry @jmcglock - I think this would remove the bad blocklists and be a positive change, but not sure what else I can do to get this merged. I will keep it open a bit longer in case the NextDNS team come back to the project but will probably close the PR by the end of the month if nobody acts on it.

**Comment by jmcglock** [comment]
It's a shame they won't accept it. Thanks for trying.

**Comment by chr-lei** [comment]
@rs @romaincointepas - one last check in on this to see if it can be merged.

**Comment by chr-lei** [comment]
I give up. Guess we’re keeping known bad blocklists for people to use.

**Pull request closed without merging**
